### ISSUE TITLE
monty hall project

### ISSUE THREAD

**Issue by Messengerwoong** [Git-practice-9/Monty_Hall_Simulation#1]
## Description
이 문제는 montly hall project를 divide and conquer해서 푸는 문제입니다.

## Tasks

- [ ] 세 개의 문과 자동차 배치하기 
 세 개의 문 중 하나를 랜덤하게 선택하여 자동차를 배치합니다.
 다른 두 문에는 염소를 배치합니다.
- [ ] 참가자의 초기 선택하기
 참가자가 처음에 어떤 문을 선택할지 입력 받습니다.
- [ ] Monty의 행동 시뮬레이션하기
 Monty는 참가자가 선택한 문이 아니면서 염소가 있는 문을 선택합니다.
- [ ] 스위치 여부 결정하기
  참가자는 선택을 유지할 것인지, 아니면 다른 문으로 스위치할 것인지 입력 받습니다.
- [ ] 게임 결과 확인하기
  참가자의 최종 선택과 문의 내용을 기반으로 결과를 확인
- [ ]전체 코드 실행하기
-  전체적인 게임 흐름을 실행

**Comment by narykkim** [comment]
위에 보시면 3번째에 #2 라고 있는데 이것저것 누르다가 있는 걸 잘못건드려가지고 저 문제 자체가 이슈 발행이 되가지고 막 뻘짓 하다가 저렇게 되었답니다ㅎㅎ 저는 저 3번째에 문의를 드리고 싶었어요ㅎ

**Comment by Messengerwoong** [comment]
문의요?ㅎㅎㅎ

**Comment by narykkim** [comment]
네 문의 드리려고 했는데 ㅎㅎ 다시 읽어보니 이해가 갑니다! 
저는 염소가 있든지 말든지 우선 문의 번호를 선택하는 것이라고 생각했는데, 다시 생각해보니 3번에 써 놓으신 거나 같은 얘기 인 것 같습니다.

**Comment by Messengerwoong** [comment]
오홍!!! 시간이 걸리더라도 2번째 프로젝트로 만들죠.!!!

**Comment by narykkim** [comment]
네네 ㅋㅋ 우리 인풋값이랑 리턴값만 좀 정할까요?

**Comment by Messengerwoong** [comment]
음.. 안 정해도 될 것 같아요. 제 의도는 코드를 제가 하고 넘겨주면 나리님이 그것 뒤에 짜고 이런 식으로 해서 완성 시키려는 의도 였어요. 마지막은 같이 해도 되고요. 함수로 !!!

**Comment by narykkim** [comment]
아! 네네!!

**Comment by Messengerwoong** [comment]
오래 걸릴 수도 있으니.. 다른 것 하고 계시다가 띵동 뜨면 하고 그래요. !

**Comment by Messengerwoong** [comment]
일단 한 개해서 pull request해놨는데 오늘은 에너지를 다 써서 자야할 듯 합니다. !!!내일 틈틈히 또 할게요!!
